// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220112140129_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("ChangeRequestSignatureUpload", b =>
                {
                    b.Property<int>("ChangeRequestsChangeRequestId")
                        .HasColumnType("int");

                    b.Property<int>("SignaturesSignatureUploadId")
                        .HasColumnType("int");

                    b.HasKey("ChangeRequestsChangeRequestId", "SignaturesSignatureUploadId");

                    b.HasIndex("SignaturesSignatureUploadId");

                    b.ToTable("ChangeRequestSignatures");
                });

            modelBuilder.Entity("DataAccessLayer.Models.ChangeRequest", b =>
                {
                    b.Property<int>("ChangeRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("AdditionalComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DetailDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasActiveRejection")
                        .HasColumnType("bit");

                    b.Property<int?>("ImpactTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("RationaleTypeId")
                        .HasColumnType("int");

                    b.Property<string>("ReasonForChange")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("RoleOther")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StatusChangeRequestStatusId")
                        .HasColumnType("int");

                    b.Property<string>("TitleSubject")
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR(255)");

                    b.Property<int?>("TrialId")
                        .HasColumnType("int");

                    b.Property<string>("TrialOther")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ChangeRequestId");

                    b.HasIndex("ImpactTypeId");

                    b.HasIndex("RationaleTypeId");

                    b.HasIndex("RoleId");

                    b.HasIndex("StatusChangeRequestStatusId");

                    b.HasIndex("TrialId");

                    b.ToTable("ChangeRequests");
                });

            modelBuilder.Entity("DataAccessLayer.Models.ChangeRequestStatus", b =>
                {
                    b.Property<int>("ChangeRequestStatusId")
                        .HasColumnType("int");

                    b.Property<string>("ChangeRequestStatusName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("ChangeRequestStatusId");

                    b.ToTable("ChangeRequestStatuses");

                    b.HasData(
                        new
                        {
                            ChangeRequestStatusId = 10,
                            ChangeRequestStatusName = "Pending Requester",
                            IsActive = true
                        },
                        new
                        {
                            ChangeRequestStatusId = 20,
                            ChangeRequestStatusName = "Pending Initial Approval",
                            IsActive = true
                        },
                        new
                        {
                            ChangeRequestStatusId = 30,
                            ChangeRequestStatusName = "Pending Development Work",
                            IsActive = true
                        },
                        new
                        {
                            ChangeRequestStatusId = 40,
                            ChangeRequestStatusName = "Pending Peer Review",
                            IsActive = true
                        },
                        new
                        {
                            ChangeRequestStatusId = 50,
                            ChangeRequestStatusName = "Pending Release",
                            IsActive = true
                        },
                        new
                        {
                            ChangeRequestStatusId = 60,
                            ChangeRequestStatusName = "Completed",
                            IsActive = true
                        },
                        new
                        {
                            ChangeRequestStatusId = 70,
                            ChangeRequestStatusName = "Abandoned",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.DecisionType", b =>
                {
                    b.Property<int>("DecisionTypeId")
                        .HasColumnType("int");

                    b.Property<string>("DecisionTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("DecisionTypeId");

                    b.ToTable("DecisionTypes");

                    b.HasData(
                        new
                        {
                            DecisionTypeId = 10,
                            DecisionTypeName = "Approved",
                            IsActive = true
                        },
                        new
                        {
                            DecisionTypeId = 20,
                            DecisionTypeName = "Rejected with Amendments",
                            IsActive = true
                        },
                        new
                        {
                            DecisionTypeId = 30,
                            DecisionTypeName = "Rejected and Abandoned",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.DevLeadChangeAuthorisation", b =>
                {
                    b.Property<int>("DevLeadChangeAuthorisationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("AdditionalComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ChangeRequestId")
                        .HasColumnType("int");

                    b.Property<string>("ChangeRequiredDecription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DecisionBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DecisionDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DecisionExplanation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DecisionTypeId")
                        .HasColumnType("int");

                    b.Property<double>("EstimatedTimeImpact")
                        .HasColumnType("float");

                    b.HasKey("DevLeadChangeAuthorisationId");

                    b.HasIndex("ChangeRequestId");

                    b.HasIndex("DecisionTypeId");

                    b.ToTable("DevLeadChangeAuthorisations");
                });

            modelBuilder.Entity("DataAccessLayer.Models.DevWorkCompleteAuthorisation", b =>
                {
                    b.Property<int>("DevWorkCompleteAuthorisationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<double>("ActualTimeImpactDays")
                        .HasColumnType("float");

                    b.Property<string>("AdditionalComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChangeDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ChangeRequestId")
                        .HasColumnType("int");

                    b.Property<string>("CommitReference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CompletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProcessDeviationReasonId")
                        .HasColumnType("int");

                    b.HasKey("DevWorkCompleteAuthorisationId");

                    b.HasIndex("ChangeRequestId");

                    b.HasIndex("ProcessDeviationReasonId");

                    b.ToTable("DevWorkCompleteAuthorisations");
                });

            modelBuilder.Entity("DataAccessLayer.Models.DevWorkReleaseAuthorisation", b =>
                {
                    b.Property<int>("DevWorkReleaseAuthorisationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("AdditionalComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ChangeRequestId")
                        .HasColumnType("int");

                    b.Property<int>("ProcessDeviationReasonId")
                        .HasColumnType("int");

                    b.Property<string>("ReleasedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReleasedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("DevWorkReleaseAuthorisationId");

                    b.HasIndex("ChangeRequestId");

                    b.HasIndex("ProcessDeviationReasonId");

                    b.ToTable("DevWorkReleaseAuthorisations");
                });

            modelBuilder.Entity("DataAccessLayer.Models.DevWorkReviewAuthorisation", b =>
                {
                    b.Property<int>("DevWorkReviewAuthorisationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("AdditionalComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ChangeRequestId")
                        .HasColumnType("int");

                    b.Property<int>("ProcessDeviationReasonId")
                        .HasColumnType("int");

                    b.Property<string>("ReviewedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReviewedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("DevWorkReviewAuthorisationId");

                    b.HasIndex("ChangeRequestId");

                    b.HasIndex("ProcessDeviationReasonId");

                    b.ToTable("DevWorkReviewAuthorisations");
                });

            modelBuilder.Entity("DataAccessLayer.Models.EmailType", b =>
                {
                    b.Property<int>("EmailTypeId")
                        .HasColumnType("int");

                    b.Property<string>("EmailTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("EmailTypeId");

                    b.ToTable("EmailTypes");

                    b.HasData(
                        new
                        {
                            EmailTypeId = 1,
                            EmailTypeName = "ChangeRequestApprovedToRequester",
                            IsActive = true
                        },
                        new
                        {
                            EmailTypeId = 2,
                            EmailTypeName = "ChangeRequestDeclinedWithAmendmentsToRequester",
                            IsActive = true
                        },
                        new
                        {
                            EmailTypeId = 3,
                            EmailTypeName = "ChangeRequestDeclinedAndAbandonedToRequester",
                            IsActive = true
                        },
                        new
                        {
                            EmailTypeId = 4,
                            EmailTypeName = "ChangeRequestCompletedToRequester",
                            IsActive = true
                        },
                        new
                        {
                            EmailTypeId = 100,
                            EmailTypeName = "ChangeRequestPendingInitialApprovalToDevLead",
                            IsActive = true
                        },
                        new
                        {
                            EmailTypeId = 101,
                            EmailTypeName = "ChangeRequestPendingSubsequentApprovalToDevLead",
                            IsActive = true
                        },
                        new
                        {
                            EmailTypeId = 200,
                            EmailTypeName = "ChangeRequestPendingDevWorkToDevTeam",
                            IsActive = true
                        },
                        new
                        {
                            EmailTypeId = 201,
                            EmailTypeName = "ChangeRequestPendingPeerReviewToDevTeam",
                            IsActive = true
                        },
                        new
                        {
                            EmailTypeId = 202,
                            EmailTypeName = "ChangeRequestPendingReleaseToDevTeam",
                            IsActive = true
                        },
                        new
                        {
                            EmailTypeId = 300,
                            EmailTypeName = "ChangeRequestPeerReviewApprovalToDev",
                            IsActive = true
                        },
                        new
                        {
                            EmailTypeId = 301,
                            EmailTypeName = "ChangeRequestPeerReviewDeclinedToDev",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.FileUpload", b =>
                {
                    b.Property<int>("FileUploadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("ChangeRequestId")
                        .HasColumnType("int");

                    b.Property<byte[]>("File")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FileHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FileUploadDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReadableFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UploadedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FileUploadId");

                    b.HasIndex("ChangeRequestId");

                    b.ToTable("FileUploads");
                });

            modelBuilder.Entity("DataAccessLayer.Models.ImpactType", b =>
                {
                    b.Property<int>("ImpactTypeId")
                        .HasColumnType("int");

                    b.Property<string>("ImpactTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("ImpactTypeId");

                    b.ToTable("ImpactTypes");

                    b.HasData(
                        new
                        {
                            ImpactTypeId = 10,
                            ImpactTypeName = "Critical",
                            IsActive = true
                        },
                        new
                        {
                            ImpactTypeId = 20,
                            ImpactTypeName = "High",
                            IsActive = true
                        },
                        new
                        {
                            ImpactTypeId = 30,
                            ImpactTypeName = "Medium",
                            IsActive = true
                        },
                        new
                        {
                            ImpactTypeId = 40,
                            ImpactTypeName = "Low",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("ChangeRequestId")
                        .HasColumnType("int");

                    b.Property<int?>("NotificationTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Recipient")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SeenDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SentDate")
                        .HasColumnType("datetime2");

                    b.HasKey("NotificationId");

                    b.HasIndex("ChangeRequestId");

                    b.HasIndex("NotificationTypeId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("DataAccessLayer.Models.NotificationType", b =>
                {
                    b.Property<int>("NotificationTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("NotificationTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NotificationTypeId");

                    b.ToTable("NotificationTypes");

                    b.HasData(
                        new
                        {
                            NotificationTypeId = 1,
                            IsActive = true,
                            NotificationTypeName = "Change Request Approved"
                        },
                        new
                        {
                            NotificationTypeId = 2,
                            IsActive = true,
                            NotificationTypeName = "Change Request Declined with Amendments"
                        },
                        new
                        {
                            NotificationTypeId = 3,
                            IsActive = true,
                            NotificationTypeName = "Change Request Decline and Abandoned"
                        },
                        new
                        {
                            NotificationTypeId = 4,
                            IsActive = true,
                            NotificationTypeName = "Change Request Completed"
                        },
                        new
                        {
                            NotificationTypeId = 100,
                            IsActive = true,
                            NotificationTypeName = "Change Request Pending Initial Approval"
                        },
                        new
                        {
                            NotificationTypeId = 101,
                            IsActive = true,
                            NotificationTypeName = "Change Request Pending Subsequent Approval"
                        },
                        new
                        {
                            NotificationTypeId = 200,
                            IsActive = true,
                            NotificationTypeName = "Change Request Pending Development Work"
                        },
                        new
                        {
                            NotificationTypeId = 201,
                            IsActive = true,
                            NotificationTypeName = "Change Request Pending Peer Review"
                        },
                        new
                        {
                            NotificationTypeId = 202,
                            IsActive = true,
                            NotificationTypeName = "Change Request Pending Release"
                        },
                        new
                        {
                            NotificationTypeId = 300,
                            IsActive = true,
                            NotificationTypeName = "Change Request Pending Peer Review"
                        },
                        new
                        {
                            NotificationTypeId = 301,
                            IsActive = true,
                            NotificationTypeName = "Change Request Pending Peer Review Declined"
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.ProcessDeviationReason", b =>
                {
                    b.Property<int>("ProcessDeviationReasonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("varchar(MAX)");

                    b.HasKey("ProcessDeviationReasonId");

                    b.ToTable("ProcessDeviationReasons");
                });

            modelBuilder.Entity("DataAccessLayer.Models.RationaleType", b =>
                {
                    b.Property<int>("RationaleTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("RationaleTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RationaleTypeId");

                    b.ToTable("RationaleTypes");

                    b.HasData(
                        new
                        {
                            RationaleTypeId = 1,
                            IsActive = true,
                            RationaleTypeName = "Change"
                        },
                        new
                        {
                            RationaleTypeId = 2,
                            IsActive = true,
                            RationaleTypeName = "Bug"
                        },
                        new
                        {
                            RationaleTypeId = 3,
                            IsActive = true,
                            RationaleTypeName = "Missing Feature"
                        },
                        new
                        {
                            RationaleTypeId = 4,
                            IsActive = true,
                            RationaleTypeName = "New Feature"
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.Rejection", b =>
                {
                    b.Property<int>("RejectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("ChangeRequestId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRejectionActive")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RejectedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RejectedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RejectionReasonTypeId")
                        .HasColumnType("int");

                    b.HasKey("RejectionId");

                    b.HasIndex("ChangeRequestId");

                    b.HasIndex("RejectionReasonTypeId");

                    b.ToTable("Rejections");
                });

            modelBuilder.Entity("DataAccessLayer.Models.RejectionReasonType", b =>
                {
                    b.Property<int>("RejectionReasonTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("CausesArchive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("RejectionReasonTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RejectionReasonTypeId");

                    b.ToTable("RejectionReasonTypes");

                    b.HasData(
                        new
                        {
                            RejectionReasonTypeId = 1,
                            CausesArchive = false,
                            IsActive = true,
                            RejectionReasonTypeName = "More Detail Needed"
                        },
                        new
                        {
                            RejectionReasonTypeId = 2,
                            CausesArchive = false,
                            IsActive = true,
                            RejectionReasonTypeName = "Incorrect Details"
                        },
                        new
                        {
                            RejectionReasonTypeId = 100,
                            CausesArchive = true,
                            IsActive = true,
                            RejectionReasonTypeName = "User Error"
                        },
                        new
                        {
                            RejectionReasonTypeId = 101,
                            CausesArchive = true,
                            IsActive = true,
                            RejectionReasonTypeName = "Duplicate Request"
                        },
                        new
                        {
                            RejectionReasonTypeId = 102,
                            CausesArchive = true,
                            IsActive = true,
                            RejectionReasonTypeName = "Already Fixed"
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("RoleName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            IsActive = true,
                            RoleName = "Trial Coordinator"
                        },
                        new
                        {
                            RoleId = 2,
                            IsActive = true,
                            RoleName = "Research Staff"
                        },
                        new
                        {
                            RoleId = 3,
                            IsActive = true,
                            RoleName = "Chief Investigator"
                        },
                        new
                        {
                            RoleId = 4,
                            IsActive = true,
                            RoleName = "Data Administrator"
                        },
                        new
                        {
                            RoleId = 1000,
                            IsActive = true,
                            RoleName = "Other"
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.SentEmail", b =>
                {
                    b.Property<int>("SentEmailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("EmailSentDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EmailTypeId")
                        .HasColumnType("int");

                    b.Property<string>("From")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HtmlBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NotificationId")
                        .HasColumnType("int");

                    b.Property<string>("PlainTextBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Recipient")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReplyTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SentEmailId");

                    b.HasIndex("EmailTypeId");

                    b.HasIndex("NotificationId");

                    b.ToTable("SentEmails");
                });

            modelBuilder.Entity("DataAccessLayer.Models.SignatureUpload", b =>
                {
                    b.Property<int>("SignatureUploadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<byte[]>("File")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FileHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FileUploadDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("UploadedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SignatureUploadId");

                    b.ToTable("SignatureUploads");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Trial", b =>
                {
                    b.Property<int>("TrialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("TrialName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TrialId");

                    b.ToTable("Trials");

                    b.HasData(
                        new
                        {
                            TrialId = 1,
                            IsActive = true,
                            TrialName = "ACTIVE"
                        },
                        new
                        {
                            TrialId = 2,
                            IsActive = true,
                            TrialName = "ASSSIST-2"
                        },
                        new
                        {
                            TrialId = 3,
                            IsActive = true,
                            TrialName = "BASIL"
                        },
                        new
                        {
                            TrialId = 4,
                            IsActive = true,
                            TrialName = "BATH-OUT-2"
                        },
                        new
                        {
                            TrialId = 5,
                            IsActive = true,
                            TrialName = "BRIGHT"
                        },
                        new
                        {
                            TrialId = 6,
                            IsActive = true,
                            TrialName = "_ChangeRequest"
                        },
                        new
                        {
                            TrialId = 7,
                            IsActive = true,
                            TrialName = "DIAMONDS"
                        },
                        new
                        {
                            TrialId = 8,
                            IsActive = true,
                            TrialName = "DISC [CTIMP]"
                        },
                        new
                        {
                            TrialId = 9,
                            IsActive = true,
                            TrialName = "_ETMA"
                        },
                        new
                        {
                            TrialId = 10,
                            IsActive = true,
                            TrialName = "Firefli"
                        },
                        new
                        {
                            TrialId = 11,
                            IsActive = true,
                            TrialName = "GYY"
                        },
                        new
                        {
                            TrialId = 12,
                            IsActive = true,
                            TrialName = "L1FE"
                        },
                        new
                        {
                            TrialId = 13,
                            IsActive = true,
                            TrialName = "MODS"
                        },
                        new
                        {
                            TrialId = 14,
                            IsActive = true,
                            TrialName = "OSTRICH"
                        },
                        new
                        {
                            TrialId = 15,
                            IsActive = true,
                            TrialName = "PACT"
                        },
                        new
                        {
                            TrialId = 16,
                            IsActive = true,
                            TrialName = "ProFHER-2"
                        },
                        new
                        {
                            TrialId = 17,
                            IsActive = true,
                            TrialName = "SHEDSSc"
                        },
                        new
                        {
                            TrialId = 18,
                            IsActive = true,
                            TrialName = "SNAP2"
                        },
                        new
                        {
                            TrialId = 19,
                            IsActive = true,
                            TrialName = "SOFFT"
                        },
                        new
                        {
                            TrialId = 20,
                            IsActive = true,
                            TrialName = "_SOPManager"
                        },
                        new
                        {
                            TrialId = 21,
                            IsActive = true,
                            TrialName = "STEPFORWARD"
                        },
                        new
                        {
                            TrialId = 22,
                            IsActive = true,
                            TrialName = "SWHSI-II"
                        },
                        new
                        {
                            TrialId = 23,
                            IsActive = true,
                            TrialName = "VenUS6"
                        },
                        new
                        {
                            TrialId = 1000,
                            IsActive = true,
                            TrialName = "Other"
                        });
                });

            modelBuilder.Entity("DevLeadChangeAuthorisationSignatureUpload", b =>
                {
                    b.Property<int>("SignaturesSignatureUploadId")
                        .HasColumnType("int");

                    b.Property<int>("devLeadChangeAuthorisationsDevLeadChangeAuthorisationId")
                        .HasColumnType("int");

                    b.HasKey("SignaturesSignatureUploadId", "devLeadChangeAuthorisationsDevLeadChangeAuthorisationId");

                    b.HasIndex("devLeadChangeAuthorisationsDevLeadChangeAuthorisationId");

                    b.ToTable("DevLeadAuthSignatures");
                });

            modelBuilder.Entity("DevWorkCompleteAuthorisationSignatureUpload", b =>
                {
                    b.Property<int>("SignaturesSignatureUploadId")
                        .HasColumnType("int");

                    b.Property<int>("devWorkCompleteAuthorisationsDevWorkCompleteAuthorisationId")
                        .HasColumnType("int");

                    b.HasKey("SignaturesSignatureUploadId", "devWorkCompleteAuthorisationsDevWorkCompleteAuthorisationId");

                    b.HasIndex("devWorkCompleteAuthorisationsDevWorkCompleteAuthorisationId");

                    b.ToTable("DevWorkCompleteAuthSignatures");
                });

            modelBuilder.Entity("DevWorkReleaseAuthorisationSignatureUpload", b =>
                {
                    b.Property<int>("SignaturesSignatureUploadId")
                        .HasColumnType("int");

                    b.Property<int>("devWorkReleaseAuthorisationsDevWorkReleaseAuthorisationId")
                        .HasColumnType("int");

                    b.HasKey("SignaturesSignatureUploadId", "devWorkReleaseAuthorisationsDevWorkReleaseAuthorisationId");

                    b.HasIndex("devWorkReleaseAuthorisationsDevWorkReleaseAuthorisationId");

                    b.ToTable("DevWorkReleaseAuthSignatures");
                });

            modelBuilder.Entity("DevWorkReviewAuthorisationSignatureUpload", b =>
                {
                    b.Property<int>("SignaturesSignatureUploadId")
                        .HasColumnType("int");

                    b.Property<int>("devWorkReviewAuthorisationsDevWorkReviewAuthorisationId")
                        .HasColumnType("int");

                    b.HasKey("SignaturesSignatureUploadId", "devWorkReviewAuthorisationsDevWorkReviewAuthorisationId");

                    b.HasIndex("devWorkReviewAuthorisationsDevWorkReviewAuthorisationId");

                    b.ToTable("DevWorkReviewAuthSignatures");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("ChangeRequestSignatureUpload", b =>
                {
                    b.HasOne("DataAccessLayer.Models.ChangeRequest", null)
                        .WithMany()
                        .HasForeignKey("ChangeRequestsChangeRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.SignatureUpload", null)
                        .WithMany()
                        .HasForeignKey("SignaturesSignatureUploadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccessLayer.Models.ChangeRequest", b =>
                {
                    b.HasOne("DataAccessLayer.Models.ImpactType", "ImpactType")
                        .WithMany()
                        .HasForeignKey("ImpactTypeId");

                    b.HasOne("DataAccessLayer.Models.RationaleType", "RationaleType")
                        .WithMany()
                        .HasForeignKey("RationaleTypeId");

                    b.HasOne("DataAccessLayer.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");

                    b.HasOne("DataAccessLayer.Models.ChangeRequestStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusChangeRequestStatusId");

                    b.HasOne("DataAccessLayer.Models.Trial", "Trial")
                        .WithMany()
                        .HasForeignKey("TrialId");

                    b.Navigation("ImpactType");

                    b.Navigation("RationaleType");

                    b.Navigation("Role");

                    b.Navigation("Status");

                    b.Navigation("Trial");
                });

            modelBuilder.Entity("DataAccessLayer.Models.DevLeadChangeAuthorisation", b =>
                {
                    b.HasOne("DataAccessLayer.Models.ChangeRequest", null)
                        .WithMany("DevLeadChangeAuthorisations")
                        .HasForeignKey("ChangeRequestId");

                    b.HasOne("DataAccessLayer.Models.DecisionType", "DecisionType")
                        .WithMany()
                        .HasForeignKey("DecisionTypeId");

                    b.Navigation("DecisionType");
                });

            modelBuilder.Entity("DataAccessLayer.Models.DevWorkCompleteAuthorisation", b =>
                {
                    b.HasOne("DataAccessLayer.Models.ChangeRequest", null)
                        .WithMany("DevWorkCompleteAuthorisations")
                        .HasForeignKey("ChangeRequestId");

                    b.HasOne("DataAccessLayer.Models.ProcessDeviationReason", "ProcessDeviationReason")
                        .WithMany()
                        .HasForeignKey("ProcessDeviationReasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessDeviationReason");
                });

            modelBuilder.Entity("DataAccessLayer.Models.DevWorkReleaseAuthorisation", b =>
                {
                    b.HasOne("DataAccessLayer.Models.ChangeRequest", null)
                        .WithMany("DevWorkReleaseAuthorisations")
                        .HasForeignKey("ChangeRequestId");

                    b.HasOne("DataAccessLayer.Models.ProcessDeviationReason", "ProcessDeviationReason")
                        .WithMany()
                        .HasForeignKey("ProcessDeviationReasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessDeviationReason");
                });

            modelBuilder.Entity("DataAccessLayer.Models.DevWorkReviewAuthorisation", b =>
                {
                    b.HasOne("DataAccessLayer.Models.ChangeRequest", null)
                        .WithMany("DevWorkReviewAuthorisations")
                        .HasForeignKey("ChangeRequestId");

                    b.HasOne("DataAccessLayer.Models.ProcessDeviationReason", "ProcessDeviationReason")
                        .WithMany()
                        .HasForeignKey("ProcessDeviationReasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessDeviationReason");
                });

            modelBuilder.Entity("DataAccessLayer.Models.FileUpload", b =>
                {
                    b.HasOne("DataAccessLayer.Models.ChangeRequest", null)
                        .WithMany("SupportingFiles")
                        .HasForeignKey("ChangeRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccessLayer.Models.Notification", b =>
                {
                    b.HasOne("DataAccessLayer.Models.ChangeRequest", "ChangeRequest")
                        .WithMany()
                        .HasForeignKey("ChangeRequestId");

                    b.HasOne("DataAccessLayer.Models.NotificationType", "NotificationType")
                        .WithMany()
                        .HasForeignKey("NotificationTypeId");

                    b.Navigation("ChangeRequest");

                    b.Navigation("NotificationType");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Rejection", b =>
                {
                    b.HasOne("DataAccessLayer.Models.ChangeRequest", null)
                        .WithMany("Rejections")
                        .HasForeignKey("ChangeRequestId");

                    b.HasOne("DataAccessLayer.Models.RejectionReasonType", "RejectionReasonType")
                        .WithMany()
                        .HasForeignKey("RejectionReasonTypeId");

                    b.Navigation("RejectionReasonType");
                });

            modelBuilder.Entity("DataAccessLayer.Models.SentEmail", b =>
                {
                    b.HasOne("DataAccessLayer.Models.EmailType", "EmailType")
                        .WithMany()
                        .HasForeignKey("EmailTypeId");

                    b.HasOne("DataAccessLayer.Models.Notification", null)
                        .WithMany("Emails")
                        .HasForeignKey("NotificationId");

                    b.Navigation("EmailType");
                });

            modelBuilder.Entity("DevLeadChangeAuthorisationSignatureUpload", b =>
                {
                    b.HasOne("DataAccessLayer.Models.SignatureUpload", null)
                        .WithMany()
                        .HasForeignKey("SignaturesSignatureUploadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.DevLeadChangeAuthorisation", null)
                        .WithMany()
                        .HasForeignKey("devLeadChangeAuthorisationsDevLeadChangeAuthorisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DevWorkCompleteAuthorisationSignatureUpload", b =>
                {
                    b.HasOne("DataAccessLayer.Models.SignatureUpload", null)
                        .WithMany()
                        .HasForeignKey("SignaturesSignatureUploadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.DevWorkCompleteAuthorisation", null)
                        .WithMany()
                        .HasForeignKey("devWorkCompleteAuthorisationsDevWorkCompleteAuthorisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DevWorkReleaseAuthorisationSignatureUpload", b =>
                {
                    b.HasOne("DataAccessLayer.Models.SignatureUpload", null)
                        .WithMany()
                        .HasForeignKey("SignaturesSignatureUploadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.DevWorkReleaseAuthorisation", null)
                        .WithMany()
                        .HasForeignKey("devWorkReleaseAuthorisationsDevWorkReleaseAuthorisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DevWorkReviewAuthorisationSignatureUpload", b =>
                {
                    b.HasOne("DataAccessLayer.Models.SignatureUpload", null)
                        .WithMany()
                        .HasForeignKey("SignaturesSignatureUploadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.DevWorkReviewAuthorisation", null)
                        .WithMany()
                        .HasForeignKey("devWorkReviewAuthorisationsDevWorkReviewAuthorisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccessLayer.Models.ChangeRequest", b =>
                {
                    b.Navigation("DevLeadChangeAuthorisations");

                    b.Navigation("DevWorkCompleteAuthorisations");

                    b.Navigation("DevWorkReleaseAuthorisations");

                    b.Navigation("DevWorkReviewAuthorisations");

                    b.Navigation("Rejections");

                    b.Navigation("SupportingFiles");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Notification", b =>
                {
                    b.Navigation("Emails");
                });
#pragma warning restore 612, 618
        }
    }
}
