// <auto-generated />
using System;
using DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251219114902_AddDataExportJobsAndStatusEnum")]
    partial class AddDataExportJobsAndStatusEnum
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApplicationUserWorkRequest", b =>
                {
                    b.Property<string>("AssigneesId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("WorkRequestsWorkRequestId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.HasKey("AssigneesId", "WorkRequestsWorkRequestId");

                    b.HasIndex("WorkRequestsWorkRequestId");

                    b.ToTable("ApplicationUserWorkRequest");

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("ApplicationUserWorkRequestHistory");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }));
                });

            modelBuilder.Entity("DataAccessLayer.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("isSystemAccount")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("AspNetUsersHistory");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }));
                });

            modelBuilder.Entity("DataAccessLayer.Models.ContactUs", b =>
                {
                    b.Property<int>("ContactUsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContactUsId"));

                    b.Property<bool>("Actioned")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ActionedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ActionedBy")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<DateTime>("Submitted")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(255)");

                    b.HasKey("ContactUsId");

                    b.ToTable("ContactUs");

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("ContactUsHistory");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }));
                });

            modelBuilder.Entity("DataAccessLayer.Models.DataExportJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("NotificationSent")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequestedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int>("TrialId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RequestedById");

                    b.HasIndex("StatusId");

                    b.HasIndex("TrialId");

                    b.ToTable("DataExportJobs");

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("DataExportJobsHistory");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }));
                });

            modelBuilder.Entity("DataAccessLayer.Models.DataExportLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DataExportBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataExportDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DataExportSuccessful")
                        .HasColumnType("bit");

                    b.Property<string>("DownloadName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExceptionText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<int?>("WorkRequestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DataExportLog", "dbo");

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("DataExportLogHistory", "dbo");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }));
                });

            modelBuilder.Entity("DataAccessLayer.Models.DataExportStatus", b =>
                {
                    b.Property<int>("DataExportStatusId")
                        .HasColumnType("int");

                    b.Property<string>("DataExportStatusName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.HasKey("DataExportStatusId");

                    b.ToTable("DataExportStatuses");

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("DataExportStatusesHistory");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }));

                    b.HasData(
                        new
                        {
                            DataExportStatusId = 0,
                            DataExportStatusName = "Queued",
                            IsActive = true
                        },
                        new
                        {
                            DataExportStatusId = 1,
                            DataExportStatusName = "Processing",
                            IsActive = true
                        },
                        new
                        {
                            DataExportStatusId = 2,
                            DataExportStatusName = "Completed",
                            IsActive = true
                        },
                        new
                        {
                            DataExportStatusId = 3,
                            DataExportStatusName = "Failed",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.EmailType", b =>
                {
                    b.Property<int>("EmailTypeId")
                        .HasColumnType("int");

                    b.Property<string>("EmailTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.HasKey("EmailTypeId");

                    b.ToTable("EmailTypes");

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("EmailTypesHistory");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }));
                });

            modelBuilder.Entity("DataAccessLayer.Models.FileUpload", b =>
                {
                    b.Property<int>("FileUploadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FileUploadId"));

                    b.Property<byte[]>("File")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FileHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FileUploadDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<string>("ReadableFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UploadedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkRequestId")
                        .HasColumnType("int");

                    b.HasKey("FileUploadId");

                    b.HasIndex("WorkRequestId");

                    b.ToTable("FileUploads");

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("FileUploadsHistory");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }));
                });

            modelBuilder.Entity("DataAccessLayer.Models.FinalAuthorisation", b =>
                {
                    b.Property<int>("FinalAuthorisationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FinalAuthorisationId"));

                    b.Property<double>("ActualTimeImpactDays")
                        .HasColumnType("float");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CompletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<int?>("ProcessDeviationReasonId")
                        .HasColumnType("int");

                    b.Property<string>("WorkReference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WorkRequestId")
                        .HasColumnType("int");

                    b.HasKey("FinalAuthorisationId");

                    b.HasIndex("ProcessDeviationReasonId");

                    b.HasIndex("WorkRequestId");

                    b.ToTable("FinalAuthorisations");

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("FinalAuthorisationsHistory");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }));
                });

            modelBuilder.Entity("DataAccessLayer.Models.InitialAuthorisation", b =>
                {
                    b.Property<int>("InitialAuthorisationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InitialAuthorisationId"));

                    b.Property<string>("DecisionBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DecisionDateTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("EstimatedTimeImpact")
                        .HasColumnType("float");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<int?>("WorkRequestId")
                        .HasColumnType("int");

                    b.Property<string>("WorkRequiredDecription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InitialAuthorisationId");

                    b.HasIndex("WorkRequestId");

                    b.ToTable("InitialAuthorisations");

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("InitialAuthorisationsHistory");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }));
                });

            modelBuilder.Entity("DataAccessLayer.Models.Label", b =>
                {
                    b.Property<int>("LabelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LabelId"));

                    b.Property<string>("HexColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("LabelDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LabelShort")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.HasKey("LabelId");

                    b.ToTable("Label");

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("LabelHistory");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }));
                });

            modelBuilder.Entity("DataAccessLayer.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<string>("BccAddresses")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NotificationTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<string>("Recipient")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SeenDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SentDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SubTaskId")
                        .HasColumnType("int");

                    b.Property<int?>("WorkRequestId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId");

                    b.HasIndex("NotificationTypeId");

                    b.HasIndex("SubTaskId");

                    b.HasIndex("WorkRequestId");

                    b.ToTable("Notifications");

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("NotificationsHistory");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }));
                });

            modelBuilder.Entity("DataAccessLayer.Models.NotificationType", b =>
                {
                    b.Property<int>("NotificationTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("NotificationTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.HasKey("NotificationTypeId");

                    b.ToTable("NotificationTypes");

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("NotificationTypesHistory");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }));

                    b.HasData(
                        new
                        {
                            NotificationTypeId = 1,
                            IsActive = true,
                            NotificationTypeName = "Work Request Approved"
                        },
                        new
                        {
                            NotificationTypeId = 2,
                            IsActive = true,
                            NotificationTypeName = "Request Requires Ammendments"
                        },
                        new
                        {
                            NotificationTypeId = 3,
                            IsActive = true,
                            NotificationTypeName = "Request Closed"
                        },
                        new
                        {
                            NotificationTypeId = 4,
                            IsActive = true,
                            NotificationTypeName = "Request Completed"
                        },
                        new
                        {
                            NotificationTypeId = 5,
                            IsActive = true,
                            NotificationTypeName = "Work Request Received"
                        },
                        new
                        {
                            NotificationTypeId = 100,
                            IsActive = true,
                            NotificationTypeName = "Request Pending Initial Approval"
                        },
                        new
                        {
                            NotificationTypeId = 101,
                            IsActive = true,
                            NotificationTypeName = "Request Re-submitted Pending Initial Approval"
                        },
                        new
                        {
                            NotificationTypeId = 200,
                            IsActive = true,
                            NotificationTypeName = "Request Pending Work"
                        },
                        new
                        {
                            NotificationTypeId = 201,
                            IsActive = true,
                            NotificationTypeName = "Assigned to Request"
                        },
                        new
                        {
                            NotificationTypeId = 202,
                            IsActive = true,
                            NotificationTypeName = "Unassigned from Request"
                        },
                        new
                        {
                            NotificationTypeId = 300,
                            IsActive = true,
                            NotificationTypeName = "New Message"
                        },
                        new
                        {
                            NotificationTypeId = 501,
                            IsActive = true,
                            NotificationTypeName = "Sub Task Created"
                        },
                        new
                        {
                            NotificationTypeId = 502,
                            IsActive = true,
                            NotificationTypeName = "Sub Task Assigned"
                        },
                        new
                        {
                            NotificationTypeId = 503,
                            IsActive = true,
                            NotificationTypeName = "Sub Task - New Message"
                        },
                        new
                        {
                            NotificationTypeId = 504,
                            IsActive = true,
                            NotificationTypeName = "Sub Task Approved"
                        },
                        new
                        {
                            NotificationTypeId = 505,
                            IsActive = true,
                            NotificationTypeName = "Sub Task Rejected"
                        },
                        new
                        {
                            NotificationTypeId = 506,
                            IsActive = true,
                            NotificationTypeName = "Sub Task Closed As Not Planned"
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.ProcessDeviationReason", b =>
                {
                    b.Property<int>("ProcessDeviationReasonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProcessDeviationReasonId"));

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("varchar(MAX)");

                    b.HasKey("ProcessDeviationReasonId");

                    b.ToTable("ProcessDeviationReasons");

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("ProcessDeviationReasonsHistory");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }));
                });

            modelBuilder.Entity("DataAccessLayer.Models.SentEmail", b =>
                {
                    b.Property<int>("SentEmailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SentEmailId"));

                    b.Property<string>("BccEmails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CcEmails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HtmlBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<string>("ReplyTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SentFrom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SentTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SentEmailId");

                    b.ToTable("SentEmails");

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("SentEmailsHistory");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }));
                });

            modelBuilder.Entity("DataAccessLayer.Models.SubTask", b =>
                {
                    b.Property<int>("SubTaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubTaskId"));

                    b.Property<string>("AssigneeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastEditedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastEditedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<int?>("StatusSubTaskStatusId")
                        .HasColumnType("int");

                    b.Property<string>("SubTaskTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkRequestId")
                        .HasColumnType("int");

                    b.HasKey("SubTaskId");

                    b.HasIndex("AssigneeId");

                    b.HasIndex("StatusSubTaskStatusId");

                    b.HasIndex("WorkRequestId");

                    b.ToTable("SubTasks");

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("SubTasksHistory");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }));
                });

            modelBuilder.Entity("DataAccessLayer.Models.SubTaskEvent", b =>
                {
                    b.Property<int>("SubTaskEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubTaskEventId"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("EventTypeSubTaskEventTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<int?>("SubTaskId")
                        .HasColumnType("int");

                    b.HasKey("SubTaskEventId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("EventTypeSubTaskEventTypeId");

                    b.HasIndex("SubTaskId");

                    b.ToTable("SubTaskEvents");

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("SubTaskEventsHistory");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }));
                });

            modelBuilder.Entity("DataAccessLayer.Models.SubTaskEventType", b =>
                {
                    b.Property<int>("SubTaskEventTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<string>("SubTaskEventTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubTaskEventTypeId");

                    b.ToTable("SubTaskEventTypes");

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("SubTaskEventTypesHistory");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }));

                    b.HasData(
                        new
                        {
                            SubTaskEventTypeId = 1,
                            IsActive = true,
                            SubTaskEventTypeName = "Message"
                        },
                        new
                        {
                            SubTaskEventTypeId = 2,
                            IsActive = true,
                            SubTaskEventTypeName = "Approve"
                        },
                        new
                        {
                            SubTaskEventTypeId = 3,
                            IsActive = true,
                            SubTaskEventTypeName = "Reject"
                        },
                        new
                        {
                            SubTaskEventTypeId = 4,
                            IsActive = true,
                            SubTaskEventTypeName = "Closed as Not Planned"
                        },
                        new
                        {
                            SubTaskEventTypeId = 5,
                            IsActive = true,
                            SubTaskEventTypeName = "Assignment"
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.SubTaskStatus", b =>
                {
                    b.Property<int>("SubTaskStatusId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<string>("SubTaskStatusName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubTaskStatusId");

                    b.ToTable("SubTaskStatuses");

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("SubTaskStatusesHistory");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }));

                    b.HasData(
                        new
                        {
                            SubTaskStatusId = 510,
                            IsActive = true,
                            SubTaskStatusName = "Open"
                        },
                        new
                        {
                            SubTaskStatusId = 520,
                            IsActive = true,
                            SubTaskStatusName = "Approved"
                        },
                        new
                        {
                            SubTaskStatusId = 600,
                            IsActive = true,
                            SubTaskStatusName = "Rejected"
                        },
                        new
                        {
                            SubTaskStatusId = 610,
                            IsActive = true,
                            SubTaskStatusName = "Closed as not planned"
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.Template", b =>
                {
                    b.Property<int>("TemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TemplateId"));

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<string>("TemplateDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplateLayout")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplateShort")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TemplateId");

                    b.ToTable("Templates");

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("TemplatesHistory");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }));
                });

            modelBuilder.Entity("DataAccessLayer.Models.TriageInfoRota", b =>
                {
                    b.Property<int>("TriageInfoRotaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TriageInfoRotaId"));

                    b.Property<string>("Afternoon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<string>("Morning")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<string>("Reserve")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TriageInfoRotaId");

                    b.ToTable("TriageInfoRotas");

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("TriageInfoRotasHistory");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }));
                });

            modelBuilder.Entity("DataAccessLayer.Models.Trial", b =>
                {
                    b.Property<int>("TrialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrialId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<int?>("TrialAttribution")
                        .HasColumnType("int");

                    b.Property<string>("TrialEmailId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TrialName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TrialOwner")
                        .HasColumnType("int");

                    b.HasKey("TrialId");

                    b.HasIndex("TrialEmailId");

                    b.ToTable("Trials");

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("TrialsHistory");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }));

                    b.HasData(
                        new
                        {
                            TrialId = 1,
                            IsActive = true,
                            TrialName = "ACTIVE"
                        },
                        new
                        {
                            TrialId = 2,
                            IsActive = true,
                            TrialName = "ASSSIST-2"
                        },
                        new
                        {
                            TrialId = 3,
                            IsActive = true,
                            TrialName = "BASIL"
                        },
                        new
                        {
                            TrialId = 4,
                            IsActive = true,
                            TrialName = "BATH-OUT-2"
                        },
                        new
                        {
                            TrialId = 5,
                            IsActive = true,
                            TrialName = "BRIGHT"
                        },
                        new
                        {
                            TrialId = 6,
                            IsActive = true,
                            TrialName = "_ChangeRequest"
                        },
                        new
                        {
                            TrialId = 7,
                            IsActive = true,
                            TrialName = "DIAMONDS"
                        },
                        new
                        {
                            TrialId = 8,
                            IsActive = true,
                            TrialName = "DISC [CTIMP]"
                        },
                        new
                        {
                            TrialId = 9,
                            IsActive = true,
                            TrialName = "_ETMA"
                        },
                        new
                        {
                            TrialId = 10,
                            IsActive = true,
                            TrialName = "Firefli"
                        },
                        new
                        {
                            TrialId = 11,
                            IsActive = true,
                            TrialName = "GYY"
                        },
                        new
                        {
                            TrialId = 12,
                            IsActive = true,
                            TrialName = "L1FE"
                        },
                        new
                        {
                            TrialId = 13,
                            IsActive = true,
                            TrialName = "MODS"
                        },
                        new
                        {
                            TrialId = 14,
                            IsActive = true,
                            TrialName = "OSTRICH"
                        },
                        new
                        {
                            TrialId = 15,
                            IsActive = true,
                            TrialName = "PACT"
                        },
                        new
                        {
                            TrialId = 16,
                            IsActive = true,
                            TrialName = "ProFHER-2"
                        },
                        new
                        {
                            TrialId = 17,
                            IsActive = true,
                            TrialName = "SHEDSSc"
                        },
                        new
                        {
                            TrialId = 18,
                            IsActive = true,
                            TrialName = "SNAP2"
                        },
                        new
                        {
                            TrialId = 19,
                            IsActive = true,
                            TrialName = "SOFFT"
                        },
                        new
                        {
                            TrialId = 20,
                            IsActive = true,
                            TrialName = "_SOPManager"
                        },
                        new
                        {
                            TrialId = 21,
                            IsActive = true,
                            TrialName = "STEPFORWARD"
                        },
                        new
                        {
                            TrialId = 22,
                            IsActive = true,
                            TrialName = "SWHSI-II"
                        },
                        new
                        {
                            TrialId = 23,
                            IsActive = true,
                            TrialName = "VenUS6"
                        },
                        new
                        {
                            TrialId = 1000,
                            IsActive = true,
                            TrialName = "Other"
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.TrialRepositoryInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("GitHubRepositoryId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<int>("TrialId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrialId");

                    b.ToTable("TrialRepositoryInfos");

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("TrialRepositoryInfosHistory");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }));
                });

            modelBuilder.Entity("DataAccessLayer.Models.WorkRequest", b =>
                {
                    b.Property<int>("WorkRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkRequestId"));

                    b.Property<long?>("AssignedTrialRepositoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DetailDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GitHubIssueNumber")
                        .HasColumnType("int");

                    b.Property<string>("LastEditedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastEditedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<int?>("ProcessDeviationReasonId")
                        .HasColumnType("int");

                    b.Property<string>("Reference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StatusWorkRequestStatusId")
                        .HasColumnType("int");

                    b.Property<int?>("TrialId")
                        .HasColumnType("int");

                    b.Property<string>("TrialOther")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WorkRequestId");

                    b.HasIndex("ProcessDeviationReasonId");

                    b.HasIndex("StatusWorkRequestStatusId");

                    b.HasIndex("TrialId");

                    b.ToTable("WorkRequests");

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("WorkRequestsHistory");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }));
                });

            modelBuilder.Entity("DataAccessLayer.Models.WorkRequestEvent", b =>
                {
                    b.Property<int>("WorkRequestEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkRequestEventId"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double?>("DurationDays")
                        .HasColumnType("float");

                    b.Property<int?>("EventTypeWorkRequestEventTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<int>("WorkRequestId")
                        .HasColumnType("int");

                    b.HasKey("WorkRequestEventId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("EventTypeWorkRequestEventTypeId");

                    b.HasIndex("WorkRequestId");

                    b.ToTable("WorkRequestEvents");

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("WorkRequestEventsHistory");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }));
                });

            modelBuilder.Entity("DataAccessLayer.Models.WorkRequestEventType", b =>
                {
                    b.Property<int>("WorkRequestEventTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<string>("WorkRequestEventTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WorkRequestEventTypeId");

                    b.ToTable("WorkRequestEventTypes");

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("WorkRequestEventTypesHistory");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }));

                    b.HasData(
                        new
                        {
                            WorkRequestEventTypeId = 1,
                            IsActive = true,
                            WorkRequestEventTypeName = "Message"
                        },
                        new
                        {
                            WorkRequestEventTypeId = 2,
                            IsActive = true,
                            WorkRequestEventTypeName = "Request Changes"
                        },
                        new
                        {
                            WorkRequestEventTypeId = 3,
                            IsActive = true,
                            WorkRequestEventTypeName = "Approve"
                        },
                        new
                        {
                            WorkRequestEventTypeId = 4,
                            IsActive = true,
                            WorkRequestEventTypeName = "Close as Completed"
                        },
                        new
                        {
                            WorkRequestEventTypeId = 5,
                            IsActive = true,
                            WorkRequestEventTypeName = "Close as Not Planned"
                        },
                        new
                        {
                            WorkRequestEventTypeId = 10,
                            IsActive = false,
                            WorkRequestEventTypeName = "Assignment"
                        },
                        new
                        {
                            WorkRequestEventTypeId = 11,
                            IsActive = false,
                            WorkRequestEventTypeName = "Label"
                        },
                        new
                        {
                            WorkRequestEventTypeId = 12,
                            IsActive = false,
                            WorkRequestEventTypeName = "GitHub Issue Attachment"
                        },
                        new
                        {
                            WorkRequestEventTypeId = 13,
                            IsActive = false,
                            WorkRequestEventTypeName = "Export work request"
                        },
                        new
                        {
                            WorkRequestEventTypeId = 20,
                            IsActive = false,
                            WorkRequestEventTypeName = "File Management"
                        },
                        new
                        {
                            WorkRequestEventTypeId = 24,
                            IsActive = false,
                            WorkRequestEventTypeName = "Subscribe"
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.WorkRequestStatus", b =>
                {
                    b.Property<int>("WorkRequestStatusId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<string>("WorkRequestStatusName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WorkRequestStatusId");

                    b.ToTable("WorkRequestStatuses");

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("WorkRequestStatusesHistory");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }));

                    b.HasData(
                        new
                        {
                            WorkRequestStatusId = 10,
                            IsActive = true,
                            WorkRequestStatusName = "Requested Changes"
                        },
                        new
                        {
                            WorkRequestStatusId = 20,
                            IsActive = true,
                            WorkRequestStatusName = "New"
                        },
                        new
                        {
                            WorkRequestStatusId = 30,
                            IsActive = true,
                            WorkRequestStatusName = "In Progress"
                        },
                        new
                        {
                            WorkRequestStatusId = 100,
                            IsActive = true,
                            WorkRequestStatusName = "Completed"
                        },
                        new
                        {
                            WorkRequestStatusId = 110,
                            IsActive = true,
                            WorkRequestStatusName = "Closed"
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.WorkRequestSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<int?>("WorkRequestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("WorkRequestId");

                    b.ToTable("WorkRequestSubscriptions");

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("WorkRequestSubscriptionsHistory");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }));
                });

            modelBuilder.Entity("LabelWorkRequest", b =>
                {
                    b.Property<int>("LabelsLabelId")
                        .HasColumnType("int");

                    b.Property<int>("WorkRequestsWorkRequestId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.HasKey("LabelsLabelId", "WorkRequestsWorkRequestId");

                    b.HasIndex("WorkRequestsWorkRequestId");

                    b.ToTable("LabelWorkRequest");

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("LabelWorkRequestHistory");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }));
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("AspNetRolesHistory");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }));
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("AspNetRoleClaimsHistory");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }));
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("AspNetUserClaimsHistory");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }));
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("AspNetUserLoginsHistory");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }));
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("AspNetUserRolesHistory");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }));
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("AspNetUserTokensHistory");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }));
                });

            modelBuilder.Entity("ApplicationUserWorkRequest", b =>
                {
                    b.HasOne("DataAccessLayer.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("AssigneesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.WorkRequest", null)
                        .WithMany()
                        .HasForeignKey("WorkRequestsWorkRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccessLayer.Models.DataExportJob", b =>
                {
                    b.HasOne("DataAccessLayer.Models.ApplicationUser", "RequestedBy")
                        .WithMany()
                        .HasForeignKey("RequestedById");

                    b.HasOne("DataAccessLayer.Models.DataExportStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.Trial", "Trial")
                        .WithMany()
                        .HasForeignKey("TrialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RequestedBy");

                    b.Navigation("Status");

                    b.Navigation("Trial");
                });

            modelBuilder.Entity("DataAccessLayer.Models.FileUpload", b =>
                {
                    b.HasOne("DataAccessLayer.Models.WorkRequest", null)
                        .WithMany("SupportingFiles")
                        .HasForeignKey("WorkRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccessLayer.Models.FinalAuthorisation", b =>
                {
                    b.HasOne("DataAccessLayer.Models.ProcessDeviationReason", "ProcessDeviationReason")
                        .WithMany()
                        .HasForeignKey("ProcessDeviationReasonId");

                    b.HasOne("DataAccessLayer.Models.WorkRequest", null)
                        .WithMany("FinalAuthorisations")
                        .HasForeignKey("WorkRequestId");

                    b.Navigation("ProcessDeviationReason");
                });

            modelBuilder.Entity("DataAccessLayer.Models.InitialAuthorisation", b =>
                {
                    b.HasOne("DataAccessLayer.Models.WorkRequest", null)
                        .WithMany("InitialAuthorisations")
                        .HasForeignKey("WorkRequestId");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Notification", b =>
                {
                    b.HasOne("DataAccessLayer.Models.NotificationType", "NotificationType")
                        .WithMany()
                        .HasForeignKey("NotificationTypeId");

                    b.HasOne("DataAccessLayer.Models.SubTask", "SubTask")
                        .WithMany()
                        .HasForeignKey("SubTaskId");

                    b.HasOne("DataAccessLayer.Models.WorkRequest", "WorkRequest")
                        .WithMany()
                        .HasForeignKey("WorkRequestId");

                    b.Navigation("NotificationType");

                    b.Navigation("SubTask");

                    b.Navigation("WorkRequest");
                });

            modelBuilder.Entity("DataAccessLayer.Models.SubTask", b =>
                {
                    b.HasOne("DataAccessLayer.Models.ApplicationUser", "Assignee")
                        .WithMany()
                        .HasForeignKey("AssigneeId");

                    b.HasOne("DataAccessLayer.Models.SubTaskStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusSubTaskStatusId");

                    b.HasOne("DataAccessLayer.Models.WorkRequest", null)
                        .WithMany("SubTasks")
                        .HasForeignKey("WorkRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignee");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("DataAccessLayer.Models.SubTaskEvent", b =>
                {
                    b.HasOne("DataAccessLayer.Models.ApplicationUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("DataAccessLayer.Models.SubTaskEventType", "EventType")
                        .WithMany()
                        .HasForeignKey("EventTypeSubTaskEventTypeId");

                    b.HasOne("DataAccessLayer.Models.SubTask", "SubTask")
                        .WithMany("SubTaskEvents")
                        .HasForeignKey("SubTaskId");

                    b.Navigation("CreatedBy");

                    b.Navigation("EventType");

                    b.Navigation("SubTask");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Trial", b =>
                {
                    b.HasOne("DataAccessLayer.Models.ApplicationUser", "TrialEmail")
                        .WithMany()
                        .HasForeignKey("TrialEmailId");

                    b.Navigation("TrialEmail");
                });

            modelBuilder.Entity("DataAccessLayer.Models.TrialRepositoryInfo", b =>
                {
                    b.HasOne("DataAccessLayer.Models.Trial", "Trial")
                        .WithMany("TrialRepositoryInfos")
                        .HasForeignKey("TrialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trial");
                });

            modelBuilder.Entity("DataAccessLayer.Models.WorkRequest", b =>
                {
                    b.HasOne("DataAccessLayer.Models.ProcessDeviationReason", "ProcessDeviationReason")
                        .WithMany()
                        .HasForeignKey("ProcessDeviationReasonId");

                    b.HasOne("DataAccessLayer.Models.WorkRequestStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusWorkRequestStatusId");

                    b.HasOne("DataAccessLayer.Models.Trial", "Trial")
                        .WithMany()
                        .HasForeignKey("TrialId");

                    b.Navigation("ProcessDeviationReason");

                    b.Navigation("Status");

                    b.Navigation("Trial");
                });

            modelBuilder.Entity("DataAccessLayer.Models.WorkRequestEvent", b =>
                {
                    b.HasOne("DataAccessLayer.Models.ApplicationUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("DataAccessLayer.Models.WorkRequestEventType", "EventType")
                        .WithMany()
                        .HasForeignKey("EventTypeWorkRequestEventTypeId");

                    b.HasOne("DataAccessLayer.Models.WorkRequest", "WorkRequest")
                        .WithMany("WorkRequestEvents")
                        .HasForeignKey("WorkRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("EventType");

                    b.Navigation("WorkRequest");
                });

            modelBuilder.Entity("DataAccessLayer.Models.WorkRequestSubscription", b =>
                {
                    b.HasOne("DataAccessLayer.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("WorkRequestSubscriptions")
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("DataAccessLayer.Models.WorkRequest", "WorkRequest")
                        .WithMany()
                        .HasForeignKey("WorkRequestId");

                    b.Navigation("ApplicationUser");

                    b.Navigation("WorkRequest");
                });

            modelBuilder.Entity("LabelWorkRequest", b =>
                {
                    b.HasOne("DataAccessLayer.Models.Label", null)
                        .WithMany()
                        .HasForeignKey("LabelsLabelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.WorkRequest", null)
                        .WithMany()
                        .HasForeignKey("WorkRequestsWorkRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DataAccessLayer.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DataAccessLayer.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DataAccessLayer.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccessLayer.Models.ApplicationUser", b =>
                {
                    b.Navigation("WorkRequestSubscriptions");
                });

            modelBuilder.Entity("DataAccessLayer.Models.SubTask", b =>
                {
                    b.Navigation("SubTaskEvents");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Trial", b =>
                {
                    b.Navigation("TrialRepositoryInfos");
                });

            modelBuilder.Entity("DataAccessLayer.Models.WorkRequest", b =>
                {
                    b.Navigation("FinalAuthorisations");

                    b.Navigation("InitialAuthorisations");

                    b.Navigation("SubTasks");

                    b.Navigation("SupportingFiles");

                    b.Navigation("WorkRequestEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
