UPDATE dbo.WorkRequests SET Reference = 'Change footer contacts' WHERE WorkRequestId = 1 ;
UPDATE dbo.WorkRequests SET Reference = 'Implement Randomised in Error correctly' WHERE WorkRequestId = 2 ;
UPDATE dbo.WorkRequests SET Reference = 'AdHoc FU Interview CRFs have disappeared' WHERE WorkRequestId = 3 ;
UPDATE dbo.WorkRequests SET Reference = 'Participant ID isn''t being checked for duplication' WHERE WorkRequestId = 4 ;
UPDATE dbo.WorkRequests SET Reference = 'Add User to ChaReq' WHERE WorkRequestId = 5 ;
UPDATE dbo.WorkRequests SET Reference = 'Add User to ChaReq' WHERE WorkRequestId = 6 ;
UPDATE dbo.WorkRequests SET Reference = 'Amend  Contact Returned data' WHERE WorkRequestId = 7 ;
UPDATE dbo.WorkRequests SET Reference = 'Remove duplicate user' WHERE WorkRequestId = 8 ;
UPDATE dbo.WorkRequests SET Reference = 'Give user access' WHERE WorkRequestId = 9 ;
UPDATE dbo.WorkRequests SET Reference = 'Give user access' WHERE WorkRequestId = 10 ;
UPDATE dbo.WorkRequests SET Reference = 'Update projects list' WHERE WorkRequestId = 11 ;
UPDATE dbo.WorkRequests SET Reference = 'Multiple issues found in testing' WHERE WorkRequestId = 12 ;
UPDATE dbo.WorkRequests SET Reference = 'Remove fax number from TMS' WHERE WorkRequestId = 13 ;
UPDATE dbo.WorkRequests SET Reference = 'Data Request for TMS' WHERE WorkRequestId = 14 ;
UPDATE dbo.WorkRequests SET Reference = 'Property tenure is missing' WHERE WorkRequestId = 15 ;
UPDATE dbo.WorkRequests SET Reference = 'Post live testing fixes' WHERE WorkRequestId = 16 ;
UPDATE dbo.WorkRequests SET Reference = 'Failing on Validation table' WHERE WorkRequestId = 17 ;
UPDATE dbo.WorkRequests SET Reference = 'Database name to contain trial name' WHERE WorkRequestId = 18 ;
UPDATE dbo.WorkRequests SET Reference = 'Update Data Export page' WHERE WorkRequestId = 19 ;
UPDATE dbo.WorkRequests SET Reference = 'Select All box' WHERE WorkRequestId = 20 ;
UPDATE dbo.WorkRequests SET Reference = 'Switch to postal missing' WHERE WorkRequestId = 21 ;
UPDATE dbo.WorkRequests SET Reference = 'Change contact date' WHERE WorkRequestId = 22 ;
UPDATE dbo.WorkRequests SET Reference = 'Multiple issues' WHERE WorkRequestId = 23 ;
UPDATE dbo.WorkRequests SET Reference = 'Bug when editing on ChaReq' WHERE WorkRequestId = 24 ;
UPDATE dbo.WorkRequests SET Reference = 'Change ulcer healed date' WHERE WorkRequestId = 25 ;
UPDATE dbo.WorkRequests SET Reference = 'Error when creating new user' WHERE WorkRequestId = 26 ;
UPDATE dbo.WorkRequests SET Reference = 'Prevent eCRF from being manually marked completed' WHERE WorkRequestId = 27 ;
UPDATE dbo.WorkRequests SET Reference = 'Remove duplicate users' WHERE WorkRequestId = 28 ;
UPDATE dbo.WorkRequests SET Reference = 'Update footer contacts' WHERE WorkRequestId = 29 ;
UPDATE dbo.WorkRequests SET Reference = 'Add user' WHERE WorkRequestId = 30 ;
UPDATE dbo.WorkRequests SET Reference = 'AspNetUsers need username to be username' WHERE WorkRequestId = 31 ;
UPDATE dbo.WorkRequests SET Reference = 'Remove received date' WHERE WorkRequestId = 32 ;
UPDATE dbo.WorkRequests SET Reference = 'Oddity with exported filenames' WHERE WorkRequestId = 33 ;
UPDATE dbo.WorkRequests SET Reference = 'Add new operative' WHERE WorkRequestId = 34 ;
UPDATE dbo.WorkRequests SET Reference = 'Reactivate Qualtrics link' WHERE WorkRequestId = 35 ;
UPDATE dbo.WorkRequests SET Reference = 'Update readme' WHERE WorkRequestId = 36 ;
